### PR TITLE
Add radioactive elements to data/elements/groups.yaml

### PR DESCRIPTION
**Pull request by dgaines2**
I have updated groups.yaml to make it possible to filter out radioactive elements.
Note: Element "No" needs to be in quotes for the yml to parse properly.

### CODE REVIEW

**Review by WalterjhShen — CHANGES_REQUESTED** [review]
We didn't include elements after Pu in our database. And we will not consider include them at any time. Please edit the list for radioactive elements to avoid inconsistency with the database.

**Comment by dgaines2** [comment]
I have updated the list so that only radioactive elements before Pu are included.

**Comment by tachyontraveler** [comment]
@WalterjhShen can you confirm whether the requested changes are made and it all looks good?

**Comment by tachyontraveler** [comment]
@WalterjhShen can you review the changes since you're the one who requested the changes?

**Review by WalterjhShen — APPROVED** [review]
LGTM

**Pull request merged**
