### PR TITLE
Reverse anonymous chemical formulae for OPTIMADE ('ABCD4' -> 'A4BCD')

### PR DESCRIPTION
**Pull request by ml-evs**
Fixes the bug mentioned in https://github.com/wolverton-research-group/qmpy/issues/128#issuecomment-979059632, where anonymous chemical formulae have the wrong order (and the OPTIMADE validator was previously not picking it up).

### CODE REVIEW

**Comment by ml-evs** [comment]
Pinging @tachyontraveler, not sure if you would have gotten a notification on the already closed issue

**Comment by tachyontraveler** [comment]
Thanks for opening the PR, @ml-evs . I need to change the query handling function as well. Currently, the queries for compounds with the anonymous formula `A4BCD` won't return materials with the generic formula `ABCD4` in our MySQL DB. I will do look into it within a couple of days from now (it's the last weeks of this quarter here with a lot of grading to do).

**Comment by tachyontraveler** [comment]
@ml-evs  Can you create a PR to merge to the `fix/optimade` branch, instead of to the `master` branch? In that way, I can do my commits and push to the same branch before merging to the `master` branch.

**Comment by ml-evs** [comment]
> @ml-evs Can you create a PR to merge to the `fix/optimade` branch, instead of to the `master` branch? In that way, I can do my commits and push to the same branch before merging to the `master` branch.
> 
> `fix/optimade` branch: https://github.com/wolverton-research-group/qmpy/tree/fix/optimade

Done!

**Pull request merged**
