### PR TITLE
change the set volume method in substitute

### PR DESCRIPTION
**Pull request by WalterjhShen**
add a function get_volume_sum_atom and change substitute volume change section

### CODE REVIEW

**Comment by hegdevinayi** [comment]
The change looks mostly good, although I think the lines 1725 and 1724 in your code should be interchanged, no?

**Comment by WalterjhShen** [comment]
Oh, yes, you are right. Should I close this pull request and add a new one?

**Comment by hegdevinayi** [comment]
No, you can simply commit changes to your master branch and it will automatically add it to the PR. Like I did there ^

**Comment by hegdevinayi** [comment]
Before I accept this PR, can you also write a test or two for this function? 

You can add/replace the `test_substitute` test in the `StructureTestCase` in this file: `qmpy/materials/tests.py` (L79 onwards). One of the examples that fail currently (so you can add it to your test) is replacing K with Be in KCl.

**Comment by WalterjhShen** [comment]
Ok, sure! I will take a look and will do that!

**Comment by hegdevinayi** [comment]
@WalterjhShen any updates on this?

**Pull request merged**
